[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''


[tool.pylint.format]
max-line-length = "88"

[tool.pylint.master]
extension-pkg-whitelist = "numpy"
# Extensions that might be of interest in the future:
# pylint.extensions.docstyle,
# pylint.extensions.check_elif,
# pylint.extensions.docparams,
load-plugins = """
pylint.extensions.mccabe,
pylint.extensions.redefined_variable_type,
pylint.extensions.overlapping_exceptions,
"""

[tool.pylint.design]
max-complexity = "14"

[tool.isort]
multi_line_output = "3"
include_trailing_comma = "true"
force_grid_wrap = "0"
use_parentheses = "true"
line_length = "88"